# Generated by Django 5.2.1 on 2025-08-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='mark_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
