# Generated by Django 5.2.1 on 2025-08-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='000', max_length=10, unique=True),
        ),
    ]
