# Generated by Django 5.2.1 on 2025-08-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='000', max_length=10, unique=True),
        ),
    ]
